### ISSUE TITLE
Utility function: Charging session statistics

### ISSUE THREAD

**Issue by cmutel** [invveritas/green_charging_emobility#8]
- [x] Plugging and unplugging time (i.e. window of opportunity)
- [x] Total energy needed
- [ ] Maximum charging rate
- [ ] Average charging rate (should be based on some reduction of maximum rate, as charging is not even over time)

**Comment by riccardozana** [comment]
Done! Results can be found in `average_charging_sessions`. Here we group by charge_log_id and compute various metrics.
